# This is the default TOML configuration for circuitchat
# It is configured for maximum privacy
[identity]
persist = false

[history]
save = false
passphrase = ""

[ui]
mention_notification_sound = false
message_notification_sound = false

[time]
24h = true
local = false
show_tz = false
show_seconds = false

[auth]
enabled = true
password = "" # It will prompt you for a password on startup if auth is enabled and this is empty

[privacy]
typing_status = false
read_receipts = false
randomize_filenames = true
session_timeout_mins = 0 # 0 means no timeout
idle_away_mins = 5 # 0 to disable, shows away status after N minutes of no input

[bridge]
enabled = false
lines = []